<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="9.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanMvcCatalog.Application\CleanMvcCatalog.Application.csproj" />
    <ProjectReference Include="..\CleanMvcCatalog.Domain\CleanMvcCatalog.Domain.csproj" />
    <ProjectReference Include="..\CleanMvcCatalog.Infra.Data\CleanMvcCatalog.Infra.Data.csproj" />
  </ItemGroup>

</Project>
